# Nomer 2 : Topic Modeling dengan LSA

<h2>Import Library</h2>

<p>Langkah pertama adalah melakukan import library yang dimana nantinya digunakan untuk membaca data mauapaun memanipulasi dan, untuk tahapan preprocessing, Tf-idf, maupun untuk LSA nya nanti.</p>

In [1]:
# data visualisation and manipulation
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns
#configure
# sets matplotlib to inline and displays graphs below the corressponding cell.
%matplotlib inline  
style.use('fivethirtyeight')
sns.set(style='whitegrid',color_codes=True)

#import nltk
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize

#preprocessing
from nltk.corpus import stopwords  #stopwords
from nltk import word_tokenize,sent_tokenize # tokenizing
from nltk.stem import PorterStemmer,LancasterStemmer  # using the Porter Stemmer and Lancaster Stemmer and others
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import WordNetLemmatizer  # lammatizer from WordNet
nltk.download('punkt')

# for named entity recognition (NER)
from nltk import ne_chunk

# vectorizers for creating the document-term-matrix (DTM)
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

# SVD
from sklearn.decomposition import TruncatedSVD

#k means
from sklearn.cluster import KMeans

#stop-words
stop_words=set(nltk.corpus.stopwords.words('indonesian'))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Arlaz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


<h2>Membaca Dokumen</h2>

<p>Setelahnya, proses yang dilakukan adalah membuka dokumen hasil Crawling yang telah dilakukan sebelumnya</p>

In [2]:
df=pd.read_csv(r'hasil_crawling.csv')

<p>Proses Selanjutnya adalah menampilkan file hasil crawling, dan dapat dilihat dibawah data hasil crawling berjumlah 15</p>

In [3]:
df

Judul  \
0   Pengaruh Retailing Mix terhadap Keputusan Pemb...   
1   PENGARUH PERSEPSI MANFAAT, PERSEPSI KEMUDAHAN,...   
2   PELAPORAN BIAYA KUALITAS UNTUK MEMINIMALKAN TE...   
3   PENGARUH KOMPETENSI DOSEN TERHADAP KINERJA DOS...   
4   PENGARUH PENGEMBANGAN KARIR TERHADAP SEMANGAT ...   
5   Analisis Inovasi Dan Keunggulan Bersaing \r\nD...   
6   PENGARUH TIPE KEPEMIMPINAN TERHADAP PRESTASI K...   
7   PENGARUH PERILAKU KONSUMEN TERHADAP KEPUTUSAN ...   
8   PENGARUH DIMENSI KUALITAS PELAYANAN TERHADAP K...   
9   ANALISIS TINGKAT RISIKO KREDIT \r\nPADA PD. BP...   
10  ANALISIS PERSEPSI BRAND ASSOCIATION MENURUT PE...   
11  PENGARUH FAKTOR-FAKTOR PELATIHAN DAN PENGEMBAN...   
12  PENGARUH KEPEMIMPINAN DAN KOMPENSASI TERHADAP ...   
13  Pengukuran Website Quality Pada Situs Sistem A...   
14  PENGARUH GAYA KEPEMIMPINAN DEMOKRATIK TERHADAP...   

                                              Abstrak  
0   Tujuan penelitian ini adalah untuk mengetahui ...  
1   Tujuan penelitian ini adalah untuk mengidentif...  
2   ABSTRAK\r\n\r\nPenelitian ini mengungkapkan be...  
3   Abstrak\r\n\r\nAththaariq, Pengaruh Kompetensi...  
4   PLN merupakan Badan Usaha Milik Negara yang be...  
5   ABSTRAK\r\n\tTujuan penelitian ini adalah mend...  
6   ABSTRAK\r\n\tDharma Abidin Syah,Kesimpulan: (1...  
7   ABSTRAK\r\nHaryono Arifin, Pengaruh Perilaku K...  
8   ABSTRAK\r\n\r\nTujuan penelitian ini adalah un...  
9   Hasil dari penelitian ini dari perhitungan Cre...  
10  Tujuan penelitian ini adalah untuk mengetahui ...  
11                                      ABSTRAK\r\...  
12  Abstrak\r\nPenelitian ini menggunakan metode k...  
13  Aplikasi nyata pemanfaatan teknologi informasi...  
14                                                NaN

<p>Dikarenakan pada data ke 15 atau index 14 data Abstraknya NaN atau kosong, maka disini data pada baris tersebut akan dihilangkan</p>

In [4]:
df.drop([14], axis=0, inplace=True)

In [5]:
df

Judul  \
0   Pengaruh Retailing Mix terhadap Keputusan Pemb...   
1   PENGARUH PERSEPSI MANFAAT, PERSEPSI KEMUDAHAN,...   
2   PELAPORAN BIAYA KUALITAS UNTUK MEMINIMALKAN TE...   
3   PENGARUH KOMPETENSI DOSEN TERHADAP KINERJA DOS...   
4   PENGARUH PENGEMBANGAN KARIR TERHADAP SEMANGAT ...   
5   Analisis Inovasi Dan Keunggulan Bersaing \r\nD...   
6   PENGARUH TIPE KEPEMIMPINAN TERHADAP PRESTASI K...   
7   PENGARUH PERILAKU KONSUMEN TERHADAP KEPUTUSAN ...   
8   PENGARUH DIMENSI KUALITAS PELAYANAN TERHADAP K...   
9   ANALISIS TINGKAT RISIKO KREDIT \r\nPADA PD. BP...   
10  ANALISIS PERSEPSI BRAND ASSOCIATION MENURUT PE...   
11  PENGARUH FAKTOR-FAKTOR PELATIHAN DAN PENGEMBAN...   
12  PENGARUH KEPEMIMPINAN DAN KOMPENSASI TERHADAP ...   
13  Pengukuran Website Quality Pada Situs Sistem A...   

                                              Abstrak  
0   Tujuan penelitian ini adalah untuk mengetahui ...  
1   Tujuan penelitian ini adalah untuk mengidentif...  
2   ABSTRAK\r\n\r\nPenelitian ini mengungkapkan be...  
3   Abstrak\r\n\r\nAththaariq, Pengaruh Kompetensi...  
4   PLN merupakan Badan Usaha Milik Negara yang be...  
5   ABSTRAK\r\n\tTujuan penelitian ini adalah mend...  
6   ABSTRAK\r\n\tDharma Abidin Syah,Kesimpulan: (1...  
7   ABSTRAK\r\nHaryono Arifin, Pengaruh Perilaku K...  
8   ABSTRAK\r\n\r\nTujuan penelitian ini adalah un...  
9   Hasil dari penelitian ini dari perhitungan Cre...  
10  Tujuan penelitian ini adalah untuk mengetahui ...  
11                                      ABSTRAK\r\...  
12  Abstrak\r\nPenelitian ini menggunakan metode k...  
13  Aplikasi nyata pemanfaatan teknologi informasi...

<p>Disini kita membuang kolom yang tidak dibutuhkan yaitu disini adalah kolom judul</p>

In [6]:
df.drop(['Judul'],axis=1,inplace=True)

In [7]:
df

Abstrak
0   Tujuan penelitian ini adalah untuk mengetahui ...
1   Tujuan penelitian ini adalah untuk mengidentif...
2   ABSTRAK\r\n\r\nPenelitian ini mengungkapkan be...
3   Abstrak\r\n\r\nAththaariq, Pengaruh Kompetensi...
4   PLN merupakan Badan Usaha Milik Negara yang be...
5   ABSTRAK\r\n\tTujuan penelitian ini adalah mend...
6   ABSTRAK\r\n\tDharma Abidin Syah,Kesimpulan: (1...
7   ABSTRAK\r\nHaryono Arifin, Pengaruh Perilaku K...
8   ABSTRAK\r\n\r\nTujuan penelitian ini adalah un...
9   Hasil dari penelitian ini dari perhitungan Cre...
10  Tujuan penelitian ini adalah untuk mengetahui ...
11                                      ABSTRAK\r\...
12  Abstrak\r\nPenelitian ini menggunakan metode k...
13  Aplikasi nyata pemanfaatan teknologi informasi...

<h2>Preprocesing Data</h2>

<p>Pada Proses ini tahap Preprocessing dilakukan dengan lemmatizer dan juga stopword.
    Proses ini dilakukan untuk menghilangkan tanda baca maupun simbol simbol yang tidak diperlukan.
</p>

In [8]:
def clean_text(text):
    le=WordNetLemmatizer()
    word_tokens=word_tokenize(text)
    tokens=[le.lemmatize(w) for w in word_tokens if w not in stop_words and len(w)>3]
    cleaned_text = " ".join(tokens)
    return cleaned_text

In [9]:
# time taking
df['Abstrak_Cleaned']=df['Abstrak'].apply(clean_text)

<p>Disini terlihat bahwa abstrak setelah proses Preprocessing bahwa hal hal yang tidak diperlukan telah  dihilangkan</p>

In [10]:
df

Abstrak  \
0   Tujuan penelitian ini adalah untuk mengetahui ...   
1   Tujuan penelitian ini adalah untuk mengidentif...   
2   ABSTRAK\r\n\r\nPenelitian ini mengungkapkan be...   
3   Abstrak\r\n\r\nAththaariq, Pengaruh Kompetensi...   
4   PLN merupakan Badan Usaha Milik Negara yang be...   
5   ABSTRAK\r\n\tTujuan penelitian ini adalah mend...   
6   ABSTRAK\r\n\tDharma Abidin Syah,Kesimpulan: (1...   
7   ABSTRAK\r\nHaryono Arifin, Pengaruh Perilaku K...   
8   ABSTRAK\r\n\r\nTujuan penelitian ini adalah un...   
9   Hasil dari penelitian ini dari perhitungan Cre...   
10  Tujuan penelitian ini adalah untuk mengetahui ...   
11                                      ABSTRAK\r\...   
12  Abstrak\r\nPenelitian ini menggunakan metode k...   
13  Aplikasi nyata pemanfaatan teknologi informasi...   

                                      Abstrak_Cleaned  
0   Tujuan penelitian pengaruh variabel Retailing ...  
1   Tujuan penelitian mengidentifikasi variabel-va...  
2   ABSTRAK Penelitian rumusan pelaporan biaya kua...  
3   Abstrak Aththaariq Pengaruh Kompetensi Dosen T...  
4   Badan Usaha Milik Negara bergerak bidang penye...  
5   ABSTRAK Tujuan penelitian mendeskripsikan inov...  
6   ABSTRAK Dharma Abidin Syah Kesimpulan Terdapat...  
7   ABSTRAK Haryono Arifin Pengaruh Perilaku Konsu...  
8   ABSTRAK Tujuan penelitian mengidentifikasi var...  
9   Hasil penelitian perhitungan Credit Risk Ratio...  
10  Tujuan penelitian persepsi brand association p...  
11  ABSTRAK Satiyah Pengaruh Faktor-faktor Pelatih...  
12  Abstrak Penelitian metode kuantitatif menekank...  
13  Aplikasi nyata pemanfaatan teknologi informasi...

<p>Proses selanjutnya ialah menghilangkan kolom yang tidak digunakan</p>

In [11]:
df.drop(['Abstrak'],axis=1,inplace=True)

In [12]:
df

Abstrak_Cleaned
0   Tujuan penelitian pengaruh variabel Retailing ...
1   Tujuan penelitian mengidentifikasi variabel-va...
2   ABSTRAK Penelitian rumusan pelaporan biaya kua...
3   Abstrak Aththaariq Pengaruh Kompetensi Dosen T...
4   Badan Usaha Milik Negara bergerak bidang penye...
5   ABSTRAK Tujuan penelitian mendeskripsikan inov...
6   ABSTRAK Dharma Abidin Syah Kesimpulan Terdapat...
7   ABSTRAK Haryono Arifin Pengaruh Perilaku Konsu...
8   ABSTRAK Tujuan penelitian mengidentifikasi var...
9   Hasil penelitian perhitungan Credit Risk Ratio...
10  Tujuan penelitian persepsi brand association p...
11  ABSTRAK Satiyah Pengaruh Faktor-faktor Pelatih...
12  Abstrak Penelitian metode kuantitatif menekank...
13  Aplikasi nyata pemanfaatan teknologi informasi...

<h2>Tfidf</h2>

<p>Pada prses ini dilakukan proses Tfidf</p>
<p>Dalam TfidfVectorizer sendiri telah terset default untuk membuat semua huruf menjadi lowercase </p>
</p>

<p>Untuk rumus Tfidf sendiri adalah sebagai berikut</p>

$w_{i, j}=t f_{i, j} \times \log \left(\frac{N}{d f_{i}}\right)$

$
\begin{aligned}
t f_{i, j} &=\text { banyaknya kata- } i \text { pada dokumen ke- } j \\
N &=\text { total dokumen } \\
d f_{i} &=\text { banyaknya dokumen yang mengandung kata ke- } i
\end{aligned}
$

In [13]:
vect =TfidfVectorizer(stop_words=stop_words,max_features=1000) # to play with. min_df,max_df,max_features etc...

In [14]:
vect_text=vect.fit_transform(df['Abstrak_Cleaned'])
words = vect.get_feature_names()

C:\Users\Arlaz\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['baiknya', 'berkali', 'kali', 'kurangnya', 'mata', 'olah', 'sekurang', 'setidak', 'tama', 'tidaknya'] not in stop_words.
  warnings.warn(
C:\Users\Arlaz\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


<p>Berikutnya disini adalah kita dapat melihat kata kata yang sering muncul atau disebut umum. </p>
<p>Kata yang sering muncul akan memeiliki skor paling kecil dari pada kata yang lain</p>

In [15]:
print(vect_text.shape)
print(vect_text)

(14, 516)
  (0, 258)	0.02013461747206666
  (0, 342)	0.03041989600152473
  (0, 447)	0.06558282473832959
  (0, 451)	0.028298502322094705
  (0, 150)	0.0525400341839688
  (0, 142)	0.0525400341839688
  (0, 22)	0.060703919033996835
  (0, 453)	0.0525400341839688
  (0, 29)	0.060703919033996835
  (0, 484)	0.14024299710474247
  (0, 86)	0.03858378085155277
  (0, 97)	0.060703919033996835
  (0, 31)	0.060703919033996835
  (0, 462)	0.0525400341839688
  (0, 54)	0.060703919033996835
  (0, 328)	0.03858378085155277
  (0, 180)	0.02462752751913675
  (0, 88)	0.11575134255465833
  (0, 283)	0.060703919033996835
  (0, 89)	0.0354800158801719
  (0, 268)	0.03858378085155277
  (0, 422)	0.03858378085155277
  (0, 113)	0.032791412369164795
  (0, 64)	0.028298502322094705
  (0, 477)	0.03041989600152473
  :	:
  (13, 228)	0.25027190223846824
  (13, 20)	0.05005438044769365
  (13, 379)	0.1001087608953873
  (13, 414)	0.05005438044769365
  (13, 435)	0.044536047233530204
  (13, 100)	0.05005438044769365
  (13, 274)	0.150163141

In [16]:
idf=vect.idf_

<p>disini dapat dilihat bahwa penelitian merupakan kata yang sering muncul</p>

In [17]:
dd=dict(zip(vect.get_feature_names(), idf))
l=sorted(dd, key=(dd).get)
print(l[0],l[-2])
print(dd['kunci'])
print(dd['wispandono'])
print(dd['wildan'])


kunci wildan
1.0
3.0149030205422647
3.0149030205422647


<h2>Latent Semantic Analysis atau LSA</h2>
<p></p>
<p>disini untuk pengimplementasian LSA dengan menggunakan SVD</p>

<p>Untuk contoh SVD adalah sebagi berikut:</p>

$$
\text { Misalkan } A=\left(\begin{array}{cc}
1 & -1 \\
0 & 1 \\
1 & 0
\end{array}\right)
\text { Tentukan Dekomposisi nilai singular A }
$$

<p>Maka hasilnya akan seperti berikut:</p>

$$
A A^{\prime}=\left(\begin{array}{cc}
1 & -1 \\
0 & 1 \\
1 & 0
\end{array}\right)\left(\begin{array}{ccc}
1 & 0 & 1 \\
-1 & 0 & 1
\end{array}\right)=\left(\begin{array}{ccc}
2 & -1 & 1 \\
-1 & 1 & 0 \\
1 & 0 & 1
\end{array}\right)
$$

In [18]:
lsa_model = TruncatedSVD(n_components=5, algorithm='randomized', n_iter=10, random_state=42)

lsa_top=lsa_model.fit_transform(vect_text)

In [19]:
print(lsa_top)
print(lsa_top.shape)

[[ 0.56325723 -0.31185761 -0.30663116 -0.21284195 -0.05738355]
 [ 0.35192685 -0.1241204  -0.03493777  0.25731728  0.09997027]
 [ 0.15905043 -0.17968417  0.28752938 -0.16631705 -0.3737704 ]
 [ 0.32783907 -0.10250827  0.21763634 -0.13865279  0.49358641]
 [ 0.42894564  0.43008771  0.1576426   0.28959261 -0.20010739]
 [ 0.13433731 -0.13402033  0.59449779 -0.23663343 -0.19095027]
 [ 0.5178398   0.47616506 -0.03334935 -0.09175598  0.15314264]
 [ 0.4140585  -0.31976306 -0.30996231 -0.11769575 -0.41649135]
 [ 0.53412019 -0.33412258 -0.14421438  0.10204025  0.07908344]
 [ 0.08260769 -0.09010578  0.48698849 -0.39714767 -0.03428273]
 [ 0.20335891 -0.2845925   0.19149525  0.53555011 -0.25432758]
 [ 0.37840665  0.51446246  0.13944044  0.18077865 -0.2480235 ]
 [ 0.62548593  0.17515681 -0.08590174 -0.27323556  0.20395752]
 [ 0.19294598 -0.30883867  0.3362438   0.39880337  0.40425409]]
(14, 5)


In [20]:
l=lsa_top[0]
print("Document 0 :")
for i,topic in enumerate(l):
  print("Topic ",i," : ",topic*100)

Document 0 :
Topic  0  :  56.32572333122779
Topic  1  :  -31.185761176789057
Topic  2  :  -30.663116218670687
Topic  3  :  -21.284195412821525
Topic  4  :  -5.738355478823403


In [21]:
print(lsa_model.components_.shape)
print(lsa_model.components_)

(5, 516)
[[ 1.69920987e-02  7.71949070e-03  3.91988708e-03 ...  1.05236423e-02
   7.71949070e-03  7.71949070e-03]
 [ 6.84697749e-04 -4.00251674e-03 -7.09009430e-03 ... -2.79324035e-02
  -4.00251674e-03 -4.00251674e-03]
 [-1.05122467e-02  9.57266340e-03  4.31663380e-02 ...  3.42576889e-02
   9.57266340e-03  9.57266340e-03]
 [ 1.63038619e-05 -6.64527471e-03 -3.83584893e-02 ...  4.42736729e-02
  -6.64527471e-03 -6.64527471e-03]
 [-3.12559728e-02  2.44344123e-02 -3.42010348e-03 ...  4.63548871e-02
   2.44344123e-02  2.44344123e-02]]


<p>Disini hanya terdapat 5 topic dikarenakan saat proses TruncatedSVD parameter untuk dimensi keluaran yang diinginkan hanya diisi 5 dan dibatasi 20 kata saja</p>

In [22]:
# most important words for each topic
vocab = vect.get_feature_names()

for i, comp in enumerate(lsa_model.components_):
    vocab_comp = zip(vocab, comp)
    sorted_words = sorted(vocab_comp, key= lambda x:x[1], reverse=True)[:20]
    print("Topic "+str(i)+": ")
    for t in sorted_words:
        print(t[0],end=" ")
    print("\n")

Topic 0: 
variabel penelitian kerja konsumen pegawai kepemimpinan signifikan pengaruh hipotesis pembelian kepuasan kompensasi nilai berpengaruh prestasi keputusan kompetensi pelayanan pengujian pengembangan 

Topic 1: 
kerja pengembangan pegawai prestasi faktor produktivitas tipe kepemimpinan pelatihan karir karyawan semangat dinas kabupaten kelautan perikanan sampang demokratis kecamatan pangarengan 

Topic 2: 
bersaing inovasi keunggulan lamongan 2011 data mengalami akademik kompetensi bank resiko optik pemasaran reza tingkat 2008 kinerja daerah biaya pelanggan 

Topic 3: 
dimensi pelanggan persepsi akademik kepuasan association brand cranberries distro kiddrock kerja pengembangan portal pakaian karir karyawan semangat banking internet indeks 

Topic 4: 
kompetensi dosen akademik kepuasan madura universitas variabel portal kinerja trunojoyo nilai pedagogik kepemimpinan indeks kompensasi kepribadian profesional administrasi importance informasi 

